### ISSUE TITLE
Which software must I use to sender the required custom package?

### ISSUE THREAD

**Issue by q2dg** [FabrizioCaldarelli/Commanduino#2]
There is a screenshot showing the "Packet sender" app in OS X (I guess)...but a similar one in Linux and Windows isn't mentioned.
Thanks

**Comment by q2dg** [comment]
Ooh, I see "Packet sender" is multi-platform and open-source. Perfect! But a line in Readme.md showing this could be convenient.

**Comment by fcaldarelli** [comment]
Thanks, I've upgraded Readme.md
